import type { Metadata } from "next";
import type { ReactNode } from "react";
import { NextThemeProvider } from "./NextThemeProvider";
import "./globals.css";

// TODO: set proper metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  // TODO: set proper language
  return (
    <html lang="en">
      <body>
        <NextThemeProvider>{children}</NextThemeProvider>
      </body>
    </html>
  );
}
